[2016-12-22 07:11:41.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:13:37.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 31 with code 0:  
[2016-12-22 07:14:17.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 31 with code 0:  
[2016-12-22 07:14:31.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 31 with code 0:  
[2016-12-22 07:17:27.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 49 with code 0:  
[2016-12-22 07:20:00.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 49 with code 0:  
[2016-12-22 07:20:58.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 51 with code 0:  
[2016-12-22 07:22:24.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 49 with code 0:  
[2016-12-22 07:22:50.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 49 with code 0:  
[2016-12-22 07:24:52.000000] -- Log level: info -- Message: message value1 value2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 49 with code 0:  
