[2016-12-22 07:24:52.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:40:57.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:41:13.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:41:47.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:42:11.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:43:39.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:43:55.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
[2016-12-22 07:44:16.000000] -- Log level: warning -- Message: message logtest1 logtest2 Exception found at D:\Development\PhpstormProjects\logger\tests\Unit\Tests\Unit\FileLoggerTest.php 30 with code 0:  
